version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:6.0.7
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'