version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongodb-chat_service
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: chat_service
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: bdung
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
