version: '3.7'

services:
  mysql-db:
    container_name: my-sql-db
    image: mysql:${MYSQL_V}
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./volumes/mysql/db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8089:80"
    depends_on:
      - mysql-db
#    environment:
#      - PMA_HOST=mysql-db
#      - PMA_PORT=3306
#      - PMA_ARBITRARY=1