version: '3.3'


volumes:
  nexus-data:

services:
    nexus3:
        container_name: 'nexus_3.30.0'
        ports:
            - '8081:8081'
        volumes:
            - 'nexus-data:/nexus-data' 
        image: sonatype/nexus3:3.30.0