version: "3.8"
services:
  database:
    image: postgres:14.4-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: db-test-dc
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    ports:
      - "5522:5432"
