version: '3.8'
services:
  redis-commander:
    container_name: redis-ui
    image: rediscommander/redis-commander:${FINAL}
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=redis
      # - REDIS_HOSTS=local:redis:6379
    depends_on:
      - cache-redis

  cache-redis:
    container_name: cache-redis
    hostname: redis
    image: redis
#    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./volumes/cache-redis:/data
volumes:
  cache:
    driver: local