version: '3'
services:
  redisinsight-and-redis:
    container_name: redisinsight-and-redis
    hostname: redis
    image: redis/redis-stack:${redisinsight_ver}
    volumes:
      - ./volumes/redis/redis-stack.conf:/redis-stack.conf
      - ./volumes/redis/data:/data
    ports:
      - "8001:8001" #port ui
      - "6379:6379" #port redis