version: '3'
services:
  redisinsight-and-redis:
    container_name: redisinsight-and-redis
    hostname: redis
    image: redis/redis-stack:latest
    volumes:
      - ./redis/redis-stack.conf:/redis-stack.conf
      - ./redis/data:/data
    ports:
      - "8001:8001"
      - "6379:6379"