version: "3.8"
services:
  seata-server:
    container_name: seata-server
    image: seataio/seata-server #2.0.0-slim #1.4.2
   # restart: always
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_REGISTER=true
      - SEATA_REGISTER_PORT=8091
      - SEATA_SERVER_PORT=8091
      - SEATA_MAX_WORKER_THREADS=100
      - SEATA_MAX_SESSIONS=1000
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry # custom configuration file registry.conf and file.conf

    #    expose:
    #      # expose ports on the container to other services within the Docker network, This means other containers can access the app service on expose.
    #      - 8091
    #      - 7091
    volumes:
      - ./volumes/seata-config.properties:/opt/seata/config/seata.properties
      - ./volumes/log:/opt/seata/log
      - ./volumes/seata-log:/root/logs/seata